import type { Result } from "@superego/global-types";
import type ExecutingJavascriptFunctionFailed from "../errors/ExecutingJavascriptFunctionFailed.js";
import type CollectionVersionId from "../ids/CollectionVersionId.js";
import type DocumentVersionId from "../ids/DocumentVersionId.js";
import type ContentSummary from "./ContentSummary.js";

export default interface DocumentVersion<Content = Record<string, unknown>> {
  id: DocumentVersionId;
  collectionVersionId: CollectionVersionId;
  /** Id of the previous version. Null if this is the first version. */
  previousVersionId: DocumentVersionId | null;
  content: Content;
  /**
   * The content summary is a Record<name: string, value: string> derived from
   * the document's content that contains its most important information, in a
   * condensed manner. The summary is used for display purposes in various UI
   * contexts.
   *
   * For example, the first property of the summary is considered to be
   * (conceptually) the "name" or "title" of the document, and is used as
   * breadcrumb in the default document view. In the default collection view,
   * summary properties are used as columns of the documents table.
   *
   * The summary is generated by user-defined function.
   */
  contentSummary: Result<ContentSummary, ExecutingJavascriptFunctionFailed>;
  createdAt: Date;
}
