import type { Result } from "@superego/global-types";
import type DocumentVersionCreator from "../enums/DocumentVersionCreator.js";
import type ContentSummaryNotValid from "../errors/ContentSummaryNotValid.js";
import type ExecutingJavascriptFunctionFailed from "../errors/ExecutingJavascriptFunctionFailed.js";
import type CollectionVersionId from "../ids/CollectionVersionId.js";
import type ConversationId from "../ids/ConversationId.js";
import type DocumentVersionId from "../ids/DocumentVersionId.js";
import type ContentSummary from "./ContentSummary.js";

type DocumentVersion<Content = Record<string, unknown>> = {
  id: DocumentVersionId;
  collectionVersionId: CollectionVersionId;
  /** Id of the previous version. Null if this is the first version. */
  previousVersionId: DocumentVersionId | null;
  /**
   * Id of the conversation in which this document version was created. Not null
   * only when createdBy === DocumentVersionCreator.Assistant.
   */
  conversationId: ConversationId | null;
  content: Content;
  /**
   * The content summary is a Record<name: string, value: string> derived from
   * the document's content that contains its most important bits of
   * information. The summary is used for display purposes in various UI
   * contexts.
   *
   * For example, the first property of the summary is considered to be
   * (conceptually) the "name" or "title" of the document, and is used as
   * breadcrumb in the default document view. In the default collection view,
   * summary properties are used as columns of the documents table.
   *
   * The summary is generated by a user-defined function.
   *
   * The names of the summary properties can be prefixed by attributes that
   * configure the behavior of the UIs that render the summary. Example:
   *
   * ```js
   * const contentSummary = {
   *   "{position:0,sortable:true,default-sort:asc} First Name": "John",
   *   "{position:1,sortable:true} Last Name": "Doe"
   * }
   * ```
   */
  contentSummary: Result<
    ContentSummary,
    ExecutingJavascriptFunctionFailed | ContentSummaryNotValid
  >;
  createdBy: DocumentVersionCreator;
  createdAt: Date;
} & (
  | { createdBy: DocumentVersionCreator.User; conversationId: null }
  | { createdBy: DocumentVersionCreator.Migration; conversationId: null }
  | {
      createdBy: DocumentVersionCreator.Assistant;
      conversationId: ConversationId;
    }
);
export default DocumentVersion;
